//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid FilterMode enumeration value. The value must be one of the defined AutoCompleteFilterMode values to be accepted. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnFilterModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnFilterModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid MinimumPopulateDelay value &apos;{0}&apos;. The value must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property SearchText. ähnelt.
        /// </summary>
        internal static string AutoComplete_OnSearchTextPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("AutoComplete_OnSearchTextPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot perform operation. ähnelt.
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid index value &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string DomainUpDown_CurrentIndex_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_CurrentIndex_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid InvalidInputAction value &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string DomainUpDown_InvalidInputAction_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_InvalidInputAction_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid ExpandDirection value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid attempt to change read-only property &quot;{0}.&quot; ähnelt.
        /// </summary>
        internal static string InvalidAttemptToChangeReadOnlyProperty {
            get {
                return ResourceManager.GetString("InvalidAttemptToChangeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property TimeItemsSelection. ähnelt.
        /// </summary>
        internal static string ListTimePickerPopup_TimeItemsSelection_ReadOnly {
            get {
                return ResourceManager.GetString("ListTimePickerPopup_TimeItemsSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid double value &apos;{0}&apos;: valid value is of double type and within decimal range. ähnelt.
        /// </summary>
        internal static string NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Increment value &apos;{0}&apos;: valid value is of double type, within decimal range, and positive ähnelt.
        /// </summary>
        internal static string NumericUpDown_EnsureValidIncrementValue_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidIncrementValue_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid DecimalPlaces value &apos;{0}&apos;: valid value is of int type and within 0 and 15 inclusive. ähnelt.
        /// </summary>
        internal static string NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The collection is currently ReadOnly and should not be modified. ähnelt.
        /// </summary>
        internal static string ObservableObjectCollection_ReadOnly {
            get {
                return ResourceManager.GetString("ObservableObjectCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid PopupButtonMode value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Picker_PopupButtonModeNotValid {
            get {
                return ResourceManager.GetString("Picker_PopupButtonModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be larger than or equal to 0. ähnelt.
        /// </summary>
        internal static string Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating ähnelt.
        /// </summary>
        internal static string RatingAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be null or a number between 0 and 1. ähnelt.
        /// </summary>
        internal static string RatingAutomationPeer_SetValue {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Star ähnelt.
        /// </summary>
        internal static string RatingItemAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingItemAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The RoutedPropertyChangingEvent cannot be canceled. ähnelt.
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spin action is not valid at this moment. ähnelt.
        /// </summary>
        internal static string Spinner_SpinNotValid {
            get {
                return ResourceManager.GetString("Spinner_SpinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid PopupMinutesInterval &apos;{0}&apos;. The interval can be set to 0 (no interval) to and including 59. ähnelt.
        /// </summary>
        internal static string TimeInput_PopupMinutesInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupMinutesInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid PopupSecondsInterval &apos;{0}&apos;.The interval can be set to 0 (no interval) to and including 59. ähnelt.
        /// </summary>
        internal static string TimeInput_PopupSecondsInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupSecondsInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set the PopupProperty in a style. Please use PopupTemplate. ähnelt.
        /// </summary>
        internal static string TimePicker_PopupSetInStyle {
            get {
                return ResourceManager.GetString("TimePicker_PopupSetInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid PopupTimeSelectionMode for this popup, value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string TimePicker_PopupTimeSelectionModeNotValid {
            get {
                return ResourceManager.GetString("TimePicker_PopupTimeSelectionModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property TimeHintContent. ähnelt.
        /// </summary>
        internal static string TimeUpDown_OnTimeHintContentChanged {
            get {
                return ResourceManager.GetString("TimeUpDown_OnTimeHintContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; cannot convert from &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot parse text &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string UpDown_ParseException {
            get {
                return ResourceManager.GetString("UpDown_ParseException", resourceCulture);
            }
        }
    }
}
