//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The modification made to the collection lead to an invalid Selection state. Please check the SelectionMode to allow zero or multiple items. ähnelt.
        /// </summary>
        internal static string Accordion_InvalidManipulationOfSelectionCollections {
            get {
                return ResourceManager.GetString("Accordion_InvalidManipulationOfSelectionCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should not signal a finish when item is not expected to perform an action. ähnelt.
        /// </summary>
        internal static string Accordion_OnActionFinish_InvalidFinish {
            get {
                return ResourceManager.GetString("Accordion_OnActionFinish_InvalidFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid ExpandDirection value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Accordion_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property SelectedIndices. ähnelt.
        /// </summary>
        internal static string Accordion_OnSelectedIndicesChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedIndicesChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set read-only property SelectedItems. ähnelt.
        /// </summary>
        internal static string Accordion_OnSelectedItemsChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("Accordion_OnSelectedItemsChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid SelectionMode value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Accordion_OnSelectionModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid SelectionSequence value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Accordion_OnSelectionSequencepropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Accordion_OnSelectionSequencepropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported collection action &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Accordion_UnsupportedCollectionAction {
            get {
                return ResourceManager.GetString("Accordion_UnsupportedCollectionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ContentTargetSize is a read-only value and is set through Accordion. ähnelt.
        /// </summary>
        internal static string AccordionItem_InvalidWriteToContentTargetSize {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToContentTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExpandDirection is a read-only value and is set through Accordion. ähnelt.
        /// </summary>
        internal static string AccordionItem_InvalidWriteToExpandDirection {
            get {
                return ResourceManager.GetString("AccordionItem_InvalidWriteToExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot modify the IsSelected property while item is locked. ähnelt.
        /// </summary>
        internal static string AccordionItem_OnIsSelectedPropertyChanged_InvalidChange {
            get {
                return ResourceManager.GetString("AccordionItem_OnIsSelectedPropertyChanged_InvalidChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Action &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidAction {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot start an action when there is no action scheduled. ähnelt.
        /// </summary>
        internal static string AccordionItem_StartAction_InvalidCall {
            get {
                return ResourceManager.GetString("AccordionItem_StartAction_InvalidCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot perform operation. ähnelt.
        /// </summary>
        internal static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid ExpandDirection value &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition &apos;{0}&apos; was not defined. ähnelt.
        /// </summary>
        internal static string TransitioningContentControl_TransitionNotFound {
            get {
                return ResourceManager.GetString("TransitioningContentControl_TransitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IsTransitioning property is read-only. ähnelt.
        /// </summary>
        internal static string TransitiotioningContentControl_IsTransitioningReadOnly {
            get {
                return ResourceManager.GetString("TransitiotioningContentControl_IsTransitioningReadOnly", resourceCulture);
            }
        }
    }
}
